Support banned relative imports
Iteo/architecture_linter pull request #25
Opened 2023-01-31 07:34 UTC by tomkad99

2024-03-22 14:28 UTC, tomkad99 commented
@bvoq Hi, 

Thanks for showing interest :) 

We will try to finish that feature in few days.

2024-05-21 10:33 UTC, RSC-88 approved these changes

2024-05-21 10:54 UTC, LukaszWojcikIteo requested changes
Missing version bump in  tools/analyzer_plugin/pubspec.yaml

2024-05-21 11:22 UTC, LukaszWojcikIteo approved these changes

2024-05-22 11:31 UTC, merged

2024-05-22 11:32 UTC, tomkad99 commented
@bvoq The new changes are ready to check from main